### ISSUE TITLE
No component factory found. Did you add it to @NgModule.entryComponents?

### ISSUE THREAD

**Issue by shitanshusharma** [NMilicic/ngx-bootstrap-product-tour#18]
ERROR in Error during template compile of 'NgxBootstrapProductTourModule'.
Function calls are not supported in decorators but 'ÉµmakeDecorator' was called in 'NgModule'.
'NgModule' calls 'ÉµmakeDecorator'
Cannot redeclare block-scoped variable 'ngDevMode'.

Angular version: 5.x.x
ngx-bootstrap-product-tour: 2.0.2

PS. These issues only happen in Prod. Works perfectly on local.

**Comment by shitanshu-sharma-avalara** [comment]
Alright fixed this issue, for once, by deleting `node_modules` and doing `npm install` again. Please suggest a permanent fix for it. But having a new issue:

`ERROR Error: No component factory found for n. Did you add it to @NgModule.entryComponents?
    at wt (main.3fb046b0776138f54df2.bundle.js:1)
    at n.resolveComponentFactory (main.3fb046b0776138f54df2.bundle.js:1)
    at n.attach (main.3fb046b0776138f54df2.bundle.js:1)
    at t.n.show (main.3fb046b0776138f54df2.bundle.js:1)
    at n.showTourStep (main.3fb046b0776138f54df2.bundle.js:1)
    at n.showStep (main.3fb046b0776138f54df2.bundle.js:1)
    at n.setCurrentStep (main.3fb046b0776138f54df2.bundle.js:1)
    at main.3fb046b0776138f54df2.bundle.js:1
    at t.invokeTask (polyfills.256e59247c71d4d4cf15.bundle.js:1)
    at Object.onInvokeTask (main.3fb046b0776138f54df2.bundle.js:1)`

Due to this, the tourStepContainers isn't displaying.

**Comment by shitanshusharma** [comment]
Alright found a workaround for this issue, by deleting `node_modules` and doing `npm install` again. Please suggest a permanent fix for it. But having a new issue:

> ERROR Error: No component factory found for n. Did you add it to @NgModule.entryComponents?
>     at wt (main.3fb046b0776138f54df2.bundle.js:1)
>     at n.resolveComponentFactory (main.3fb046b0776138f54df2.bundle.js:1)
>     at n.attach (main.3fb046b0776138f54df2.bundle.js:1)
>     at t.n.show (main.3fb046b0776138f54df2.bundle.js:1)
>     at n.showTourStep (main.3fb046b0776138f54df2.bundle.js:1)
>     at n.showStep (main.3fb046b0776138f54df2.bundle.js:1)
>     at n.setCurrentStep (main.3fb046b0776138f54df2.bundle.js:1)
>     at main.3fb046b0776138f54df2.bundle.js:1
>     at t.invokeTask (polyfills.256e59247c71d4d4cf15.bundle.js:1)
>     at Object.onInvokeTask (main.3fb046b0776138f54df2.bundle.js:1)

Due to this, the tourStepContainer isn't displaying. I think it's because dynamic loading of the tour steps and Angular fails to recognize it. Please suggest a solution for it

**Comment by lacastorine** [comment]
after coping source files from lib dir directly to my project (not as npm module, but as sources) building in prod\aot works fine... so it should be smth wrong only with bundled npm module \ tool for creating npm module...

and yes, the problem is with creating dynamic ngx-boostrap popover despite the fact that it is added to entryComponents in module...

**Comment by shitanshusharma** [comment]
Thanks a lor for replying. 
Yes, the problem is with the bundled npm module. I did spend sometime finding a fix for it but due to time constraints, I had to switch the library.
Thank-you once again for spending time on it!
